"""empty message

Revision ID: b508b6439fed
Revises: b2de119783d5
Create Date: 2024-06-15 01:49:19.588102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b508b6439fed'
down_revision = 'b2de119783d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('purchase_location', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('item_category_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_items_item_category_id', 'item_category', ['item_category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_items_item_category_id', type_='foreignkey')
        batch_op.drop_column('item_category_id')
        batch_op.drop_column('purchase_location')
        batch_op.drop_column('purchase_date')

    op.drop_table('item_category')
    # ### end Alembic commands ###
